### ISSUE TITLE
use higher rez hashtag image on login screen

### ISSUE THREAD

**Issue by daredia** [Zesty-Stocking/Zesty-Stocking#40]

**Comment by daredia** [comment]
@NerdDiffer to upload various versions/sizes of this image

**Comment by NerdDiffer** [comment]
### dark, transparent

![hashtag-dark-transparent](https://cloud.githubusercontent.com/assets/5211680/17086564/a706fa1e-51aa-11e6-8f5c-c03f96ba599c.png)

### white, transparent

Very hard to see. Its in between the two horizontal lines below.

_Below this line_

---

![hashtag-white-transparent](https://cloud.githubusercontent.com/assets/5211680/17086565/a9afba30-51aa-11e6-935d-244c6756cc05.png)

---

_Above this line_

**Comment by daredia** [comment]
closing as not necessary
